version: "3.7"
services:
    api:
        container_name: api-monterroir
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: always
        ports:
            - "3000:3000"
        networks:
            - netapi
            - netbdd

    bdd:
        container_name: mysql-monterroir
        image: mysql:latest
        restart: always
        networks:
            - netbdd
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: monterroir
            MYSQL_USER: monterroir
            MYSQL_PASSWORD: monterroirpassword
        volumes:
            - volbdd:/var/lib/mysql
        ports:
            - "3306:3306"
    
    phpmyadmin:
        container_name: phpmyadmin-monterroir
        image: phpmyadmin:latest
        depends_on:
            - bdd
        restart: always
        networks:
            - netbdd
        ports:
            - "8080:80"
        environment:
            PMA_HOST: bdd
            PMA_PORT: 3306
            PMA_USER: monterroir
            PMA_PASSWORD: monterroirpassword
            PMA_PMADB: monterroir
            UPLOAD_LIMIT: 20M

networks:
    netapi:
    netbdd:
    netsocketio:

volumes:
    volbdd:
        driver: local
        driver_opts: 
            o: bind
            type: none
            device: /home/paulin/docker-monterroir/bdd-data
