version: "3.7"

services:
    api:
        container_name: api-monterroir
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: always
        ports:
            - "3000:3000"
        networks:
            - netapi
            - netbdd
        env_file: .ENV.development

    bdd:
        container_name: mysql-monterroir
        image: mysql:latest
        restart: always
        networks:
            - netbdd
        env_file: .ENV.development
        volumes:
            - volbdd:/var/lib/mysql
        ports:
            - "3306:3306"
    
    phpmyadmin:
        container_name: phpmyadmin-monterroir
        image: phpmyadmin:latest
        depends_on:
            - bdd
        restart: always
        networks:
            - netbdd
        ports:
            - "8080:80"
        env_file: .ENV.development

networks:
    netapi:
    netbdd:
    netsocketio:

volumes:
    volbdd:
        driver: local
        driver_opts: 
            o: bind
            type: none
            device: /home/paulin/docker-monterroir/bdd-data
