services:
    api:
        container_name: api-monterroir
        build:
            context: .
            dockerfile: ./Dockerfile
            target: prod
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.monterroir-api-prod.rule=Host(`api.monterroir.local`) && PathPrefix(`/`)"
          - "traefik.http.routers.monterroir-api-prod.entrypoints=web"
        restart: always
        networks:
            - netapi
            - net-reverse-proxy
        env_file: .ENV.production

    bdd:
        container_name: mysql-monterroir
        image: mysql:8.0
        restart: always
        networks:
            - netapi
        volumes:
            - volbdd:/var/lib/mysql
        env_file: .ENV.production

networks:
    netapi:
      name: monterroir-prod-api
    net-reverse-proxy:
      name: net-reverse-proxy
      external: true

volumes:
    volbdd:
        driver: local
        driver_opts: 
            o: bind
            type: none
            device: /home/paulin/docker-monterroir/bdd-data
