services:
  api-recette:
    container_name: api-recette-monterroir
    image: ghcr.io/tpk-inde/monterroir-api:recette
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monterroir-api-recette.rule=Host(`api-recette.monterroir.local`) && PathPrefix(`/`)"
      - "traefik.http.routers.monterroir-api-recette.entrypoints=web"
    restart: always
    networks:
      - netapi-recette
      - net-reverse-proxy
    env_file: .ENV.recette

  bdd-recette:
    container_name: mysql-recette-monterroir
    image: mysql:8.0
    restart: always
    networks:
      - netapi-recette
    volumes:
      - volbdd-recette:/var/lib/mysql
    env_file: .ENV.recette

networks:
  netapi-recette:
    name: monterroir-recette-api
  net-reverse-proxy:
    name: net-reverse-proxy
    external: true

volumes:
  volbdd-recette:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/docker-monterroir/bdd-data-recette
