name: cicd
run-name: CICD
on:
  push:
      branches: [ main, recette, develop ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASS: ${{ secrets.DB_PASS }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_NAME: ${{ secrets.DB_NAME }}
  TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
  DB_MUSER: ${{ secrets.DB_MUSER }}
  DB_MPASS: ${{ secrets.DB_MPASS }}
  DB_MURL: ${{ secrets.DB_MURL }}
  DB_MNAME: ${{ secrets.DB_MNAME }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/cache@v3
          with:
            path: |
             ./node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        - run: |
            npm install
            npx tsc
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
        - uses: actions/checkout@v3
        - uses: actions/cache@v3
          with:
            path: |
              ./node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        - run: |
            npm run test
  package-production:
    runs-on: ubuntu-latest
    needs: test
    environment: production
    if: github.ref_name == 'main'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/tpk-inde/monterroir-api:latest
  package-recette:
    runs-on: ubuntu-latest
    needs: test
    environment: recette
    if: github.ref_name == 'recette'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/tpk-inde/monterroir-api:recette